// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Oasis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250303131827_Migrate")]
    partial class Migrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Oasis.Data.Models.Amenity", b =>
                {
                    b.Property<int>("amenity_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("item_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rsv_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("amenity_id");

                    b.HasIndex("item_id");

                    b.HasIndex("rsv_id");

                    b.ToTable("Amenity");
                });

            modelBuilder.Entity("Oasis.Data.Models.AmenityItem", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("item_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("item_id");

                    b.ToTable("AmenityItem");
                });

            modelBuilder.Entity("Oasis.Data.Models.Discount", b =>
                {
                    b.Property<int>("discount_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("discount_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("discount_rate")
                        .HasColumnType("REAL");

                    b.HasKey("discount_id");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Oasis.Data.Models.Guest", b =>
                {
                    b.Property<int>("guest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("guest_contactno")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("guest_dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("guest_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("guest_fname")
                        .HasColumnType("TEXT");

                    b.Property<string>("guest_gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("guest_lname")
                        .HasColumnType("TEXT");

                    b.Property<string>("guest_password")
                        .HasColumnType("TEXT");

                    b.HasKey("guest_id");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("Oasis.Data.Models.Notification", b =>
                {
                    b.Property<int>("notif_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("guest_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notif_content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("notif_date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("notif_status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("notif_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("staff_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("notif_id");

                    b.HasIndex("guest_id");

                    b.HasIndex("staff_id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Oasis.Data.Models.Payment", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("discount_id")
                        .HasColumnType("INTEGER");

                    b.Property<float>("payment_amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("payment_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("staff_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("payment_id");

                    b.HasIndex("discount_id");

                    b.HasIndex("staff_id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Oasis.Data.Models.Reservation", b =>
                {
                    b.Property<int>("rsv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("guest_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("payment_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("room_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("rsv_checkin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("rsv_checkout")
                        .HasColumnType("TEXT");

                    b.Property<string>("rsv_status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("rsv_id");

                    b.HasIndex("guest_id");

                    b.HasIndex("payment_id");

                    b.HasIndex("room_id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Oasis.Data.Models.Review", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("guest_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("review_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("review_feedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("review_rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("room_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("review_id");

                    b.HasIndex("guest_id");

                    b.HasIndex("room_id");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Oasis.Data.Models.Room", b =>
                {
                    b.Property<int>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("guest_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("room_no")
                        .HasColumnType("INTEGER");

                    b.Property<int>("room_status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("room_id");

                    b.HasIndex("guest_id");

                    b.HasIndex("type_id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Oasis.Data.Models.RoomType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("type_category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("type_price")
                        .HasColumnType("REAL");

                    b.HasKey("type_id");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("Oasis.Data.Models.Service", b =>
                {
                    b.Property<int>("service_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("rsv_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("service_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("staff_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("service_id");

                    b.HasIndex("rsv_id");

                    b.HasIndex("staff_id");

                    b.HasIndex("type_id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Oasis.Data.Models.ServiceType", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("type_price")
                        .HasColumnType("REAL");

                    b.HasKey("type_id");

                    b.ToTable("ServiceType");
                });

            modelBuilder.Entity("Oasis.Data.Models.Staff", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("staff_contactno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_dob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_fname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_lname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("staff_position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("staff_id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Oasis.Data.Models.Amenity", b =>
                {
                    b.HasOne("Oasis.Data.Models.AmenityItem", "amenityItem")
                        .WithMany()
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.Reservation", "reservation")
                        .WithMany()
                        .HasForeignKey("rsv_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("amenityItem");

                    b.Navigation("reservation");
                });

            modelBuilder.Entity("Oasis.Data.Models.Notification", b =>
                {
                    b.HasOne("Oasis.Data.Models.Guest", "guest")
                        .WithMany()
                        .HasForeignKey("guest_id");

                    b.HasOne("Oasis.Data.Models.Staff", "staff")
                        .WithMany()
                        .HasForeignKey("staff_id");

                    b.Navigation("guest");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Oasis.Data.Models.Payment", b =>
                {
                    b.HasOne("Oasis.Data.Models.Discount", "discount")
                        .WithMany()
                        .HasForeignKey("discount_id");

                    b.HasOne("Oasis.Data.Models.Staff", "staff")
                        .WithMany()
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("discount");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Oasis.Data.Models.Reservation", b =>
                {
                    b.HasOne("Oasis.Data.Models.Guest", "guest")
                        .WithMany()
                        .HasForeignKey("guest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.Room", "room")
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("guest");

                    b.Navigation("payment");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Oasis.Data.Models.Review", b =>
                {
                    b.HasOne("Oasis.Data.Models.Guest", "guest")
                        .WithMany()
                        .HasForeignKey("guest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.Room", "room")
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("guest");

                    b.Navigation("room");
                });

            modelBuilder.Entity("Oasis.Data.Models.Room", b =>
                {
                    b.HasOne("Oasis.Data.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("guest_id");

                    b.HasOne("Oasis.Data.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Oasis.Data.Models.Service", b =>
                {
                    b.HasOne("Oasis.Data.Models.Reservation", "reservation")
                        .WithMany()
                        .HasForeignKey("rsv_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.Staff", "staff")
                        .WithMany()
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oasis.Data.Models.ServiceType", "serviceType")
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("reservation");

                    b.Navigation("serviceType");

                    b.Navigation("staff");
                });
#pragma warning restore 612, 618
        }
    }
}
